### ISSUE TITLE
Fails to build with boost >= 1.87

### ISSUE THREAD

**Issue by berolinux** [luceneplusplus/LucenePlusPlus#208]
Boost versions up to 1.86 are ok.
Building with boost 1.87 results in

```
In file included from /home/bero/abf/luceneplusplus/BUILD/lucene++-3.0.9-build/LucenePlusPlus-rel_3.0.9/src/core/document/NumericField.cpp:1:
In file included from /home/bero/abf/luceneplusplus/BUILD/lucene++-3.0.9-build/LucenePlusPlus-rel_3.0.9/build/src/core/cotire/lucene++_CXX_prefix.hxx:4:
In file included from /home/bero/abf/luceneplusplus/BUILD/lucene++-3.0.9-build/LucenePlusPlus-rel_3.0.9/build/src/core/cotire/lucene++_CXX_prefix.cxx:4:
In file included from /home/bero/abf/luceneplusplus/BUILD/lucene++-3.0.9-build/LucenePlusPlus-rel_3.0.9/src/core/include/LuceneInc.h:23:
In file included from /home/bero/abf/luceneplusplus/BUILD/lucene++-3.0.9-build/LucenePlusPlus-rel_3.0.9/include/lucene++/Lucene.h:26:
In file included from /usr/include/boost/variant.hpp:17:
In file included from /usr/include/boost/variant/variant.hpp:2308:
/usr/include/boost/variant/detail/variant_io.hpp:57:14: error: invalid operands to binary expression ('std::basic_ostream<wchar_t>' and 'const boost::shared_ptr<Lucene::Reader>')
   57 |         out_ << operand;
      |         ~~~~ ^  ~~~~~~~
```

**Comment by StormBytePP** [comment]
Attaching full build log (Gentoo system, compiling with llvm-19 and using boost-1.87.0)
[build.log](https://github.com/user-attachments/files/18142314/build.log)

**Comment by StormBytePP** [comment]
Any updates on this? It is preventing me a system update :(

**Comment by christian-heusel** [comment]
@StormBytePP Could you test the MR that I have linked? I tried my best to port this to the new boost API but I'm not too sure that all is correct 😅 
This was done because `lucene++` was one of the missing packages in the Arch Linux boost 1.87.0 bost todo: https://archlinux.org/todo/boost-1870-rebuild/

**Comment by StormBytePP** [comment]
This bug seems unrelated, as I've applied the patch from #210 and still getting OP's error

**Comment by christian-heusel** [comment]
Yes I maybe should have clarified that I have also backported the mentioned boost fix (https://github.com/boostorg/smart_ptr/commit/e7433ba54596da97cb7859455cd37ca140305a9c) to our version of boost.
