### ISSUE TITLE
Compile errors with boost_1_51_0

### ISSUE THREAD

**Issue by arkagod** [luceneplusplus/LucenePlusPlus#30]
Error listing from VS

Config.h
# define BOOST_FILESYSTEM_VERSION 3

---

1>.\util\FileUtils.cpp(167) : error C2039: 'wdirectory_iterator' : is not a member of 'boost::filesystem'
1>.\util\FileUtils.cpp(207) : error C2039: 'directory_string' : is not a member of 'boost::filesystem::path'

and more...

**Comment by trupper** [comment]
When compiling LucenePlusPlus, cmake produces the following errors:
This is a build on Windows 8.1 using Visual Studio 2015.

 Could not find the following Boost libraries:

         boost_date_time
         boost_filesystem
         boost_iostreams
         boost_regex
         boost_system
         boost_thread

I've been trying to compile as follows:

cmake -Wno-dev -G "Visual Studio 14 2015 Win64" -DBOOST_LIBRARYDIR=c:\tools\boost_1_64_0\stage\lib -DBOOST_INCLUDE_DIR=c:\tools\boost_1_64_0\boost

and 

I've tried setup environment variables, as shown:

set BOOST_ROOT=c:\tools\boost_1_64_0
set BOOST_INCLUDEDIR=c:\tools\boost_1_64_0\boost
set BOOST_LIBRARYDIR=c:\tools\boost_1_64_0\stage\lib

Any help would be appreciated.
