### ISSUE TITLE
Clarify usage for "int64_t"?

### ISSUE THREAD

**Issue by elfring** [luceneplusplus/LucenePlusPlus#55]
How should the following error message be resolved?

```
elfring@Sonne:~/Projekte/Bau/Lucene++> LANG=C make
[  1%] Built target googletest
[  1%] Building CXX precompiled header src/core/cotire/lucene++_CXX_prefix.hxx.gch
<command-line>:0:7: warning: missing whitespace after the macro name [enabled by default]
In file included from /home/elfring/Projekte/Lucene++/lokal/src/core/include/LuceneInc.h:18:0,
                 from /home/elfring/Projekte/Bau/Lucene++/src/core/cotire/lucene++_CXX_prefix.hxx:4:
/home/elfring/Projekte/Lucene++/lokal/include/Lucene.h:33:14: error: 'int64_t' is already declared in this scope
 using boost::int64_t;
              ^
CMake Error at /home/elfring/Projekte/Lucene++/lokal/cmake/cotire.cmake:1522 (message):
  Error 1 precompiling
  /home/elfring/Projekte/Bau/Lucene++/src/core/cotire/lucene++_CXX_prefix.hxx.
Call Stack (most recent call first):
  /home/elfring/Projekte/Lucene++/lokal/cmake/cotire.cmake:2892 (cotire_precompile_prefix_header)


make[2]: *** [src/core/cotire/lucene++_CXX_prefix.hxx.gch] Error 1
make[1]: *** [src/core/CMakeFiles/lucene++.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by vootey** [comment]
- gentoo
- boost 1.56.0
- gcc 4.8.4 + 4.9.2
- cmake 3.1.0

I would like to use lucene++ and also experience this issue. Any idea how to workaround this?

**Comment by tswcode** [comment]
The compile error is still there, can't build lucene++ 3.0.7. I need it for the new poedit.

Specs:
* Linux oriongl64 4.1.0-gentoo #1 SMP Tue Jun 23 11:40:48 CEST 2015 x86_64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz GenuineIntel GNU/Linux
* boost 1.56.0 (also not working with 1.57.0)
* x86_64-pc-linux-gnu-4.9.3
* cmake 3.3.0
* `CFLAGS="-march=corei7 -O2 -mno-avx"`

Please support us.
