### ISSUE TITLE
build error with boost 1.70

### ISSUE THREAD

**Issue by rezso** [luceneplusplus/LucenePlusPlus#122]
The 3.0.7 release build with boost 1.70 fails:

[ 54%] Linking CXX executable searchfiles
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::mem_error'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::this_thread::interruption_point()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread::native_handle()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::do_assign(wchar_t const*, wchar_t const*, unsigned int)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::get_mem_block()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::mapped_file_source::data() const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::deflated'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::stream_error'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::version_error'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib_error::check(int)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::mapped_file_source::mapped_file_source()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::this_thread::disable_interruption::~disable_interruption()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::is_combining_implementation(unsigned short)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::okay'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::xdeflate(int)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::get_default_error_string(boost::regex_constants::error_type)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path::m_append_separator_if_needed()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::last_write_time(boost::filesystem::path const&, long, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::stream_end'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::no_flush'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path::filename() const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `typeinfo for boost::detail::thread_data_base'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::detail::get_current_thread_data()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread::joinable() const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::mapped_file_source::is_open() const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::xinflate(int)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::detail::thread_data_base::~thread_data_base()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::zlib_base()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread::detach()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::raise_runtime_error(std::runtime_error const&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread_detail::enter_once_region(boost::once_flag&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::put_mem_block(void*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::mapped_file_source::close()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::mapped_file_source::open_impl(boost::iostreams::basic_mapped_file_params<boost::iostreams::detail::path> const&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::data_error'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread::join_noexcept()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::best_compression'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::buf_error'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::construct_init(boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::directory_entry::m_get_status(boost::system::error_code*) const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path::codecvt()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::~zlib_base()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::default_strategy'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path::m_erase_redundant_separator(unsigned long)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread_detail::commit_once_region(boost::once_flag&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread::start_thread_noexcept()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::sync_flush'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::this_thread::yield()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > > > const&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `vtable for boost::detail::thread_data_base'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::re_detail_107000::verify_options(unsigned int, boost::regex_constants::_match_flags)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::this_thread::disable_interruption::disable_interruption()'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::thread_detail::rollback_once_region(boost::once_flag&)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::path::parent_path() const'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::finish'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: ../core/liblucene++.so.3.0.7: undefined reference to `boost::iostreams::zlib::default_compression'
collect2: error: ld returned 1 exit status

**Comment by zethon** [comment]
I'm running into a similar issue. I believe you need to link against the zlib libraries which are not included with boost.  I'm trying to find pre-compiled binaries for my environment but so far no luck, so I may have to try my hand at building them myself.

**Comment by dont-push-me** [comment]
I also encountered the same problem, how to solve it

**Comment by alanw** [comment]
I can't reproduce this, sorry.

**Comment by Lelelo1** [comment]
I think homebrew and macport might install boost in different location

**Comment by solanki0616** [comment]
> I'm running into a similar issue. I believe you need to link against the zlib libraries which are not included with boost. I'm trying to find pre-compiled binaries for my environment but so far no luck, so I may have to try my hand at building them myself.

---Hi, I Am also getting some similar issue, can you help
![Uploading Screenshot 2023-03-01 at 4.43.29 PM.png…]()

**Comment by solanki0616** [comment]
<img width="1728" alt="Screenshot 2023-03-01 at 4 43 19 PM" src="https://user-images.githubusercontent.com/108324484/222127018-cef419ce-2c57-4afd-9b48-490f0ec836b8.png">
